### ISSUE TITLE
The speed command should have a separate privilege.

### ISSUE THREAD

**Issue by jhcole** [FozLand/chat_next#1]
Speed originally required fly. This doesn't work in Fozland because everyone can earn fly, but the server can't handle everyone having speed. Its currently tied to teleport, but it would be better as its own privilege. Perhaps a "physics" should be created to allow changing speed as well as the other physics settings jump and gravity.

**Comment by mootpoint** [comment]
We can create the physics privilege then tie it to gravity when that is implemented

**Comment by jhcole** [comment]
Closed by ae94d59ab5c67f727864ddc89c33d90d132a5727.
