### ISSUE TITLE
Look into new tp command

### ISSUE THREAD

**Issue by mootpoint** [FozLand/chat_next#5]
something along this lines, tp x -100 moves you along -x 100 nodes, tp y 100 moves you up 100 etc...

**Comment by mootpoint** [comment]
on this note: had suggestion to allow players /gox /go similar to /sethome /home.

**Comment by jhcole** [comment]
How would /go be different than /tp?

**Comment by mootpoint** [comment]
from what mok suggested use it exactly like /home /sethome. but he wants more than two, i know i would find this useful as well to save different places or look into a nameable bookmark feature

**Comment by jhcole** [comment]
I think this might be too much for regular players. They can already set 3 different personal home locations.
1. the home button in the craft guide
2. /home command
3. a bed and /die command

Besides those three, players can use travelnets and elevators. However, I can see where this would be useful for players who already have the teleport priv.

**Comment by mootpoint** [comment]
That's what we were thinking, as well. Also the directional teleport for
players with the priv

**Comment by mootpoint** [comment]
upon further reflection, tpx to move in a direction x nodes may be a bad idea, most players that earn teleport do not have noclip, this would place them into situations that would be regrettable. closing this issue
